### ISSUE TITLE
Cayo Perico issues

### ISSUE THREAD

**Issue by CHRISPLAYZ434** [SilentSal0/Silent-Night#1]
Instant finish at least for me has always crashed as soon as I use it, women's bag does the transaction error, and the cooldown killer simply does not work. Everything else works just fine. Hope this helps.

**Comment by SilentSal0** [comment]
1) Instant Finish works correctly for me and for all ppl I know, maybe the problem is in your internet connection, since it requires stable good internet.
2) Women's Bag doesn't cause transaction error. Transaction error is caused by overlooting. Maximum payout per player for Cayo Perico is $2,550,000.
3) Cooldown Killer issue is known. The reason why it doesn't work is not clear, because for some people you just need to click on the function outside the submarine and after a few minutes Pavel will send a message that you can rob El Roobio's ass again. And for some other ppl you'll need to change session or even reboot the game.

**Comment by CHRISPLAYZ434** [comment]
thank you very much for the feedback and have a great day
